name: 'Slack Notify Stale PRs'
author: 'Kaplan'
description: 'send slack notification on stale PRs'
inputs:
  stale_label:
    description: 'label to check for in PRs'
    required: false
    default: 'stale'
  base_branch:
    description: 'Base branch of the PR'
    required: false
    default: 'main'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stale_label }}
    - ${{ inputs.base_branch }}
